version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 30
    allow:
    - dependency-type: all
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 30
    allow:
      - dependency-type: all
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
