version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 30
    allow:
    - dependency-type: all
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    schedule:
      interval: daily
      time: "03:00"
  - package-ecosystem: npm
    directory: "/"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 30
    allow:
      - dependency-type: all
