version: "2"
exclude_patterns:
  - "db/**/*"
  - "log/**/*"
  - "node_modules/**/*"
  - "public/**/*"
  - "tmp/**/*"
  - "vendor/**/*"
plugins:
  rubocop:
    enabled: false
    channel: beta
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: false
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - CUSTOM
  markdownlint:
    enabled: false
  stylelint:
    enabled: false
