version: "2"
exclude_patterns:
  - "db/**/*"
  - "log/**/*"
  - "node_modules/**/*"
  - "public/**/*"
  - "tmp/**/*"
  - "vendor/**/*"
plugins:
  rubocop:
    enabled: true
    channel: beta
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
    channel: 'eslint-8'
    config:
      extensions:
        - .es6
        - .js
        - .jsx
        - .mjs
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - CUSTOM
  markdownlint:
    enabled: false
  stylelint:
    enabled: true
    channel: 'stylelint-14-15-0'
